### ISSUE TITLE
How dose the "Angle" Param work?

### ISSUE THREAD

**Issue by quanxin** [DavidMcLaughlin208/PixelSorting#5]
Hi here is a consultation :).
i'm working on the Pixel Sort effect, and i am stucked in the "Angle" Adjustment item.
i think i can rotate image to change the sort direction only when the angle value is  particular such as 90/180 degree and so on
but how can i change the sort direction to some ordinary angle value such as 30/45 degree

I would be grateful if I could get some inspiration~

**Comment by DavidMcLaughlin208** [comment]
I use the OpenCV library to actually rotate the image at an arbitrary angle. Because you cannot rotate a 2d grid (the pixels of an image) cleanly at an arbitrary angle, there will be some color interpolation.

For this app I rotate the image using the angle param value, sort it horizontally, and then unrotate using the negative of the angle param value. 

The code to do this is here: https://github.com/DavidMcLaughlin208/PixelSorting/blob/main/src/PSImage.cpp#L60

**Comment by quanxin** [comment]
thanks for your replay and help :)
